1. **Exercise on Functions:** <br>
 1.1. Create a Python program that converts between different units of measurement.

In [ ]:
def convert_length(value, from_unit, to_unit):
    """
    Converts a length value from one unit to another.

    Parameters:
        value (float): The value to be converted.
        from_unit (str): The unit to convert from ('m' for meters, 'ft' for feet).
        to_unit (str): The unit to convert to ('m' for meters, 'ft' for feet).

    Returns:
        float: The converted value.
    """
    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084  # 1 meter = 3.28084 feet
    elif from_unit == 'ft' and to_unit == 'm':
        return value / 3.28084  # 1 foot = 0.3048 meters
    else:
        raise ValueError("Unsupported length conversion.")


def convert_weight(value, from_unit, to_unit):
    """
    Converts a weight value from one unit to another.

    Parameters:
        value (float): The value to be converted.
        from_unit (str): The unit to convert from ('kg' for kilograms, 'lbs' for pounds).
        to_unit (str): The unit to convert to ('kg' for kilograms, 'lbs' for pounds).

    Returns:
        float: The converted value.
    """
    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462  # 1 kilogram = 2.20462 pounds
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / 2.20462  # 1 pound = 0.453592 kilograms
    else:
        raise ValueError("Unsupported weight conversion.")


def convert_volume(value, from_unit, to_unit):
    """
    Converts a volume value from one unit to another.

    Parameters:
        value (float): The value to be converted.
        from_unit (str): The unit to convert from ('L' for liters, 'gal' for gallons).
        to_unit (str): The unit to convert to ('L' for liters, 'gal' for gallons).

    Returns:
        float: The converted value.
    """
    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172  # 1 liter = 0.264172 gallons
    elif from_unit == 'gal' and to_unit == 'L':
        return value / 0.264172  # 1 gallon = 3.78541 liters
    else:
        raise ValueError("Unsupported volume conversion.")


def main():
    print("Unit Conversion Program")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        # Prompt user to choose conversion type
        choice = int(input("Choose the type of conversion (1-3): "))
        if choice not in [1, 2, 3]:
            raise ValueError("Invalid choice. Please select 1, 2, or 3.")

        # Prompt user to input value
        value = float(input("Enter the value to convert: "))

        # Perform conversion based on user choice
        if choice == 1:
            print("Length Conversion Options:")
            print("1. Meters (m) to Feet (ft)")
            print("2. Feet (ft) to Meters (m)")
            sub_choice = int(input("Choose the conversion (1-2): "))
            if sub_choice == 1:
                result = convert_length(value, 'm', 'ft')
                print(f"{value} meters = {result:.2f} feet")
            elif sub_choice == 2:
                result = convert_length(value, 'ft', 'm')
                print(f"{value} feet = {result:.2f} meters")
            else:
                raise ValueError("Invalid choice for length conversion.")

        elif choice == 2:
            print("Weight Conversion Options:")
            print("1. Kilograms (kg) to Pounds (lbs)")
            print("2. Pounds (lbs) to Kilograms (kg)")
            sub_choice = int(input("Choose the conversion (1-2): "))
            if sub_choice == 1:
                result = convert_weight(value, 'kg', 'lbs')
                print(f"{value} kilograms = {result:.2f} pounds")
            elif sub_choice == 2:
                result = convert_weight(value, 'lbs', 'kg')
                print(f"{value} pounds = {result:.2f} kilograms")
            else:
                raise ValueError("Invalid choice for weight conversion.")

        elif choice == 3:
            print("Volume Conversion Options:")
            print("1. Liters (L) to Gallons (gal)")
            print("2. Gallons (gal) to Liters (L)")
            sub_choice = int(input("Choose the conversion (1-2): "))
            if sub_choice == 1:
                result = convert_volume(value, 'L', 'gal')
                print(f"{value} liters = {result:.2f} gallons")
            elif sub_choice == 2:
                result = convert_volume(value, 'gal', 'L')
                print(f"{value} gallons = {result:.2f} liters")
            else:
                raise ValueError("Invalid choice for volume conversion.")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()

Unit Conversion Program
1. Length
2. Weight
3. Volume
Choose the type of conversion (1-3): 2
Enter the value to convert: 234
Weight Conversion Options:
1. Kilograms (kg) to Pounds (lbs)
2. Pounds (lbs) to Kilograms (kg)
Choose the conversion (1-2): 2
234.0 pounds = 106.14 kilograms


1.2. Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list of float): The list of numbers to sum.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list of float): The list of numbers to average.

    Returns:
        float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list of float): The list of numbers to search.

    Returns:
        float: The maximum value in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list of float): The list of numbers to search.

    Returns:
        float: The minimum value in the list.
    """
    return min(numbers)


def main():
    print("Mathematical Operations Program")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        # Prompt user to choose an operation
        choice = int(input("Choose the operation (1-4): "))
        if choice not in [1, 2, 3, 4]:
            raise ValueError("Invalid choice. Please select 1, 2, 3, or 4.")

        # Prompt user to input a list of numbers
        input_numbers = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(num) for num in input_numbers.split()]

        if not numbers:
            raise ValueError("Empty list. Please enter at least one number.")

        # Perform the selected operation
        if choice == 1:
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif choice == 2:
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()

Mathematical Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Choose the operation (1-4): 1
Enter a list of numbers separated by spaces: 1 2 4 6 7
The sum of the numbers is: 20.0


2. **Exercise on List Manipulation:** <br>
 2.1. Extract Every Other Element:

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element from the original list.
    """
    return lst[::2]


# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)
print(result)

[1, 3, 5]


2.2. Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index and ending at another specified index (inclusive).

    Parameters:
        lst (list): The input list.
        start (int): The starting index (inclusive).
        end (int): The ending index (inclusive).

    Returns:
        list: The sublist from start to end (inclusive).
    """
    return lst[start:end + 1]


# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = get_sublist(example_list, 2, 4)
print(result)

[3, 4, 5]


2.3. Remove the First and Last Elements:

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
        lst (list): The input list.

    Returns:
        list: The sublist without the first and last elements.
    """
    return lst[1:-1]


# Example usage
example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print(result)

[2, 3, 4]


2.4. Get the First n Elements:

In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract from the beginning of the list.

    Returns:
        list: The first n elements of the list.
    """
    return lst[:n]


# Example usage
example_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(example_list, n)
print(result)

[1, 2, 3]


2.5. Extract Elements from the End:

In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract from the end of the list.

    Returns:
        list: The last n elements of the list.
    """
    return lst[-n:]


# Example usage
example_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(example_list, n)
print(result)

[4, 5]


2.6. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
    """
    Extracts a list of elements in reverse order, starting from the second-to-last element and skipping one element in between.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]


# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(example_list)
print(result)

[5, 3, 1]


3. **Exercise on Nested List:** <br>
 2.1. Flatten a Nested List:

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single-dimensional list.

    Parameters:
        lst (list): The nested list to flatten.

    Returns:
        list: A flattened version of the input list.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            flattened.extend(flatten(item))  # Recursively flatten the nested list
        else:
            flattened.append(item)  # Add non-list items directly
    return flattened


# Example usage
example_list = [[1, 2], [3, 4], [5]]
result = flatten(example_list)
print(result)

[1, 2, 3, 4, 5]


2.2. Accessing Nested List Elements:

In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
        lst (list): The nested list.
        indices (list): A list of indices representing the position of the desired element.

    Returns:
        The element at the specified position in the nested list.
    """
    result = lst
    for index in indices:
        result = result[index]  # Traverse the nested list using the indices
    return result


# Example usage
example_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(example_list, indices)
print(result)

6


2.3. Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list, regardless of depth.

    Parameters:
        lst (list): The nested list.

    Returns:
        int or float: The sum of all elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            total += sum_nested(item)  # Recursively sum the nested list
        else:
            total += item  # Add non-list items directly
    return total


# Example usage
example_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(example_list)
print(result)

21


2.4. Remove Specific Element from a Nested List:

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): The nested list.
        elem: The element to remove.

    Returns:
        list: The modified list with all occurrences of `elem` removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            result.append(remove_element(item, elem))  # Recursively remove the element from the nested list
        elif item != elem:  # Keep items that are not equal to `elem`
            result.append(item)
    return result


# Example usage
example_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(example_list, elem)
print(result)

[[1], [3], [4, 5]]


2.5. Find the Maximum Element in a Nested List:

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
        lst (list): The nested list.

    Returns:
        int or float: The maximum element in the nested list.
    """
    max_val = float('-inf')  # Initialize with negative infinity
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            current_max = find_max(item)  # Recursively find the maximum in the nested list
            if current_max > max_val:
                max_val = current_max
        elif item > max_val:  # Compare non-list items with the current maximum
            max_val = item
    return max_val


# Example usage
example_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(example_list)
print(result)

6


2.6. Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts the occurrences of a specific element in a nested list.

    Parameters:
        lst (list): The nested list.
        elem: The element to count.

    Returns:
        int: The number of occurrences of `elem` in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            count += count_occurrences(item, elem)  # Recursively count occurrences in the nested list
        elif item == elem:  # Increment count if the item matches `elem`
            count += 1
    return count


# Example usage
example_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(example_list, elem)
print(result)

3


2.7. Flatten a List of Lists of Lists:

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
        lst (list): The deeply nested list.

    Returns:
        list: A single flattened list.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            flattened.extend(deep_flatten(item))  # Recursively flatten the nested list
        else:
            flattened.append(item)  # Add non-list items directly
    return flattened


# Example usage
example_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(example_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


2.8. Nested List Average:

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): The nested list.

    Returns:
        float: The average of all elements in the nested list.
    """
    def flatten(lst):
        """
        Helper function to flatten a nested list into a single list.
        """
        flattened = []
        for item in lst:
            if isinstance(item, list):  # Check if the item is a list
                flattened.extend(flatten(item))  # Recursively flatten the nested list
            else:
                flattened.append(item)  # Add non-list items directly
        return flattened

    flattened_list = flatten(lst)  # Flatten the nested list
    if not flattened_list:  # Handle empty list case
        return 0
    return sum(flattened_list) / len(flattened_list)  # Calculate the average


# Example usage
example_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(example_list)
print(result)

3.5


3. **Basic Vector and Matrix Operation with Numpy.** <br>
 3.1. Array Creation:

In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)

# Task 2: Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All ones 4x2 array:")
print(ones_array)

# Task 3: Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 5)  # Shape: 3x3, Fill value: 5
print("\n3. Array filled with value 5:")
print(fill_value_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros array with same shape and type as given array:")
print(zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\n5. Ones array with same shape and type as given array:")
print(ones_like_array)

# Task 6: Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy array from list:")
print(numpy_array)

1. Empty 2x2 array:
[[3.19794636e-316 0.00000000e+000]
 [2.22809558e-312 2.54639495e-312]]

2. All ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 5:
[[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros array with same shape and type as given array:
[[0 0]
 [0 0]]

5. Ones array with same shape and type as given array:
[[1 1]
 [1 1]]

6. Converted NumPy array from list:
[1 2 3 4]


3.2. Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# Task 1: Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:")
print(array_10_to_49)

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:")
print(matrix_3x3)

# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:")
print(identity_matrix)

# Task 4: Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array of size 30 and its mean:")
print(random_array)
print("Mean:", mean_value)

# Task 5: Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 random array and its min and max values:")
print(random_10x10)
print("Min:", min_value)
print("Max:", max_value)

# Task 6: Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0, so 5th element is at index 4
print("\n6. Zero array of size 10 with 5th element replaced by 1:")
print(zero_array)

# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# Task 8: Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0  # Set the inner elements to 0
print("\n8. 2D array with 1 on the border and 0 inside:")
print(border_array)

# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set odd rows, even columns to 1
checkerboard[::2, 1::2] = 1  # Set even rows, odd columns to 1
print("\n9. 8x8 checkerboard pattern:")
print(checkerboard)

1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30 and its mean:
[0.61440846 0.27535174 0.38261028 0.67241471 0.85238581 0.54961459
 0.5108396  0.82160911 0.35148745 0.50424657 0.16210641 0.05300129
 0.10386472 0.21868353 0.99556523 0.18778024 0.3596772  0.88850271
 0.79925122 0.10355261 0.78041193 0.71116788 0.57889334 0.78421519
 0.86806067 0.31455037 0.47760517 0.91841554 0.35584765 0.41732209]
Mean: 0.5204481101562174

5. 10x10 random array and its min and max values:
[[0.36724255 0.75981086 0.84867964 0.35521504 0.88326754 0.46587984
  0.88621072 0.2153944  0.15234563 0.25538566]
 [0.83662537 0.37597499 0.14428944 0.13578896 0.09945893 0.88595351
  0.1981547  0.53000104 0.09447898 0.43595765]
 [0.53952571 0.10240601 0.8

3.3. Array Operations:

In [ ]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
add_result = x + y
print("1. Addition of x and y:")
print(add_result)

# Task 2: Subtract the two arrays
subtract_result = x - y
print("\n2. Subtraction of x and y:")
print(subtract_result)

# Task 3: Multiply the array with any integer
multiply_result = x * 3  # Multiply x by 3
print("\n3. Multiplication of x by 3:")
print(multiply_result)

# Task 4: Find the square of each element of the array
square_result = np.square(x)
print("\n4. Square of each element of x:")
print(square_result)

# Task 5: Find the dot product
dot_v_w = np.dot(v, w)  # Dot product of v and w
dot_x_v = np.dot(x, v)  # Dot product of x and v
dot_x_y = np.dot(x, y)  # Dot product of x and y
print("\n5. Dot products:")
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:")
print(dot_x_y)

# Task 6: Concatenate x and y along row, and v and w along column
concatenate_row = np.concatenate((x, y), axis=0)  # Along rows
concatenate_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)  # Along columns
print("\n6. Concatenation:")
print("Concatenate x and y along row:")
print(concatenate_row)
print("Concatenate v and w along column:")
print(concatenate_col)

# Task 7: Concatenate x and v
try:
    concatenate_x_v = np.concatenate((x, v))
    print("\n7. Concatenate x and v:")
    print(concatenate_x_v)
except ValueError as e:
    print("\n7. Error when concatenating x and v:")
    print(e)

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x by 3:
[[ 3  6]
 [ 9 15]]

4. Square of each element of x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 11]
 [10 12]]

7. Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


3.4. Matrix Operations:

In [ ]:
# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A−1 = I
A_inv = np.linalg.inv(A)  # Inverse of A
identity_matrix = np.dot(A, A_inv)  # A.A−1
print("1. A.A−1:")
print(identity_matrix)

# Task 2: Prove AB ≠ BA
AB = np.dot(A, B)  # AB
BA = np.dot(B, A)  # BA
print("\n2. AB:")
print(AB)
print("BA:")
print(BA)
print("AB ≠ BA:", not np.array_equal(AB, BA))

# Task 3: Prove (AB)^T = B^T A^T
AB_transpose = AB.T  # (AB)^T
B_transpose_A_transpose = np.dot(B.T, A.T)  # B^T A^T
print("\n3. (AB)^T:")
print(AB_transpose)
print("B^T A^T:")
print(B_transpose_A_transpose)
print("(AB)^T == B^T A^T:", np.array_equal(AB_transpose, B_transpose_A_transpose))

1. A.A−1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
AB ≠ BA: True

3. (AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]
(AB)^T == B^T A^T: True


In [ ]:
# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X using inverse method: X = A^(-1) . B
A_inv = np.linalg.inv(A)  # Inverse of A
X = np.dot(A_inv, B)  # X = A^(-1) . B
print("\nSolution using Inverse Method:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


Solution using Inverse Method:
x = 2.0
y = 1.0
z = -2.0


In [ ]:
# Solve for X using np.linalg.solve
X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:")
print("x =", X_solve[0])
print("y =", X_solve[1])
print("z =", X_solve[2])


Solution using np.linalg.solve:
x = 2.0
y = 1.0000000000000002
z = -2.0


# Experiment: How Fast is Numpy?
 **1. Element-wise Addition:**

In [1]:
#Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000.
import time
import random

# Define the size of the lists
size = 1_000_000

# Generate two lists with random integers
list1 = [random.randint(0, 100) for _ in range(size)]
list2 = [random.randint(0, 100) for _ in range(size)]

# Measure the time taken for element-wise addition using list comprehension
start_time = time.time()

result = [a + b for a, b in zip(list1, list2)]

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using Python lists: 0.089078 seconds


In [2]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the arrays
size = 1_000_000

# Generate two NumPy arrays with random integers
array1 = np.random.randint(0, 100, size)
array2 = np.random.randint(0, 100, size)

# Measure the time taken for element-wise addition using NumPy
start_time = time.time()

result_array = array1 + array2  # Vectorized operation

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using NumPy arrays: 0.005590 seconds


**2. Element-wise Multiplication**

In [3]:
#Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time
import random

# Define the size of the lists
size = 1_000_000

# Generate two lists with random integers
list1 = [random.randint(0, 100) for _ in range(size)]
list2 = [random.randint(0, 100) for _ in range(size)]

# Measure the time taken for element-wise multiplication using list comprehension
start_time = time.time()

result = [a * b for a, b in zip(list1, list2)]  # Multiplication operation

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.6f} seconds")


Time taken for element-wise multiplication using Python lists: 0.064225 seconds


In [4]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the arrays
size = 1_000_000

# Generate two NumPy arrays with random integers
array1 = np.random.randint(0, 100, size)
array2 = np.random.randint(0, 100, size)

# Measure the time taken for element-wise multiplication using NumPy
start_time = time.time()

result_array = array1 * array2  # Vectorized multiplication

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for element-wise multiplication using NumPy arrays: 0.005445 seconds


**3. Dot Product**

In [5]:
# Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time
import random

# Define the size of the lists
size = 1_000_000

# Generate two lists with random integers
list1 = [random.randint(0, 100) for _ in range(size)]
list2 = [random.randint(0, 100) for _ in range(size)]

# Measure the time taken for computing the dot product using Python lists
start_time = time.time()

dot_product = sum(a * b for a, b in zip(list1, list2))  # Manual dot product calculation

end_time = time.time()

# Print the time taken
print(f"Time taken for dot product using Python lists: {end_time - start_time:.6f} seconds")

Time taken for dot product using Python lists: 0.070568 seconds


In [6]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the arrays
size = 1_000_000

# Generate two NumPy arrays with random integers
array1 = np.random.randint(0, 100, size)
array2 = np.random.randint(0, 100, size)

# Measure the time taken for computing the dot product using NumPy
start_time = time.time()

dot_product = np.dot(array1, array2)  # Optimized dot product calculation

end_time = time.time()

# Print the time taken
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for dot product using NumPy arrays: 0.002212 seconds


**4. Matrix Multiplication**

In [7]:
#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.

import time
import random

# Define the size of the matrices
size = 1000

# Generate two 1000x1000 matrices with random integers
matrix1 = [[random.randint(0, 100) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(0, 100) for _ in range(size)] for _ in range(size)]

# Initialize the result matrix with zeros
result = [[0] * size for _ in range(size)]

# Measure the time taken for matrix multiplication using nested loops
start_time = time.time()

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()

# Print the time taken
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.6f} seconds")

Time taken for matrix multiplication using Python lists: 298.519130 seconds


In [8]:
#Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the matrices
size = 1000

# Generate two 1000x1000 matrices with random integers using NumPy
matrix1 = np.random.randint(0, 100, (size, size))
matrix2 = np.random.randint(0, 100, (size, size))

# Measure the time taken for matrix multiplication using NumPy
start_time = time.time()

# Matrix multiplication using NumPy's dot product function
result = np.dot(matrix1, matrix2)

end_time = time.time()

# Print the time taken
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time:.6f} seconds")

Time taken for matrix multiplication using NumPy: 1.581538 seconds
